version: "3.9"


services:
  django:
    build: ./backend/app/
    command: python /app/backend/manage.py runserver 0.0.0.0:8000
    container_name: django
    image: django:app
    ports:
      - 8000:8000 
    volumes:
      - ./backend/app/:/app/backend
  flet:
    build: ./frontend/
    command: python /app/frontend/main.py -d
    ports:
      - 5000:5000
    volumes:
      - ./frontend/:/app/frontend
    depends_on:
      - django
      
    
  
  